### PR TITLE
Add Spider for Ministerio del Ambiente

### PR DESCRIPTION
**Pull request by matiskay**
url: http://visitas.minam.gob.pe/frmConsulta.aspx

### CODE REVIEW

**Comment by matiskay** [comment]
Related to https://github.com/aniversarioperu/manolo_scraper/issues/38

**Comment by aniversarioperu** [comment]
@matiskay puedes chequear el spider Ambiente? creo que no está escrapenado todo. Para el 2015-09-01 hay 52 visitas según la web, pero el spider solo logra escrapear 15 items.

**Comment by matiskay** [comment]
@aniversarioperu, I will take a look at it today.

**Comment by matiskay** [comment]
@aniversarioperu, it was my fault. I remember that I changed the callback `parse_items` to `parse`. We don't have tests to test intermediate requests. Our current tests are for parse method. Anyways, I fixed the problem.

**Comment by matiskay** [comment]
@aniversarioperu, once you merge this pull request I can update the other pull requests. Next time I will separate the commits. There was not need to work on top of the other commits. Sorry about that.

**Pull request merged**
